export const TABLE_TURMA = "TURMA";
export const TABLE_ESTUDANTE = "ESTUDANTE";
export const TABLE_DOCENTE = "DOCENTE";
export const TABLE_HOBBY = "HOBBY";
export const TABLE_ESTUDANTE_HOBBY = "ESTUDANTE_HOBBY";
export const TABLE_ESPECIALIDADE = "DOCENTE";
export const TABLE_DOCENTE_ESPECIALIDADE = "DOCENTE_ESPECIALIDADE";
